#cloud-config
package_update: true
package_upgrade: true
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}
runcmd:
  - curl "https://binaries.twingate.com/connector/setup.sh" | sudo TWINGATE_ACCESS_TOKEN="${tg_connector_token}" TWINGATE_REFRESH_TOKEN="${tg_connector_refresh_token}" TWINGATE_URL="https://${tg_network}.twingate.com" bash
